    DATA SEGMENT
    A DD 01000100H,02000200H,030003000H,03000300H
    SUM DD ?
  DATA ENDS
  CODE SEGMENT
    ASSUME:CS: CODE DS:DATA
    START:
    MOV AX,DATA
    MOV DS,AX
    MOV CX,4
    MOV AX,0 
    MOV DX,0
    MOV SI,0
    LABEL1: ADD AX,WORD PTR A[SI]  
           
            ADC DX,WORD PTR A[SI+2]
            ADD SI,04H
           LOOP LABEL1
           MOV SUM,AX
           MOV SUM+2,DX 
    CODE ENDS
  END START
